version: "3.7"
services:
  client:
    image: c
    ports:
      - "3000:5000"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./html:/usr/share/nginx/html
    # depends_on:
    #   - php
    container_name: cc
  server:
    image: s
    env_file:
      - .env
     
    ports:
      - "1337:1337"
    depends_on:
      - db
    container_name: ss
    restart: always
    # volumes:
    #   - ./html:/var/www/html

  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./new_database.sql:/docker-entrypoint-initdb.d/new_database.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: db

  
