name: Client CI/CD
on:
  pull_request: 
  push:
    branches:
    - main 
jobs:
    build_docker_image: 
        runs-on: ubuntu-latest
        steps:
            - name: Get repository files
              uses: actions/checkout@v4
            - name: Build Docker image
              run: |
                cd client
                docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/shop-client:latest .
                docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
                docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/shop-client:latest ${{ secrets.DOCKER_HUB_USERNAME }}/shop-client:latest
                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shop-client:latest  
             