name: Server CI/CD
on:
  push:
    branches:
    - main 
jobs:
    build_docker_image: 
        runs-on: ubuntu-latest
        steps:
            - name: Get repository files
              uses: actions/checkout@v4
            - name: Build Docker image
              run: |
                cd server
                docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/shop-server:latest .
                docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shop-server:latest  