name: Deploy React App
on: 
  push:
    branches:
      - main
    # paths-ignore: 
    #   - '.github/**'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository files@v2
              uses: actions/checkout@v4
            # - name: Cache Primes
            #   uses: actions/cache@v4
            #   with:
            #     path: ~/.npm
            #     key: node-modules-${{ hashFiles('client/packege-lock.json') }}
            - name: Install dependencies
              run: |
                cd client
                npm ci
            - name: Test app
              run: |
                cd client
                npm run test
    lint: 
        runs-on: ubuntu-latest
        steps:
            - name: Get repository files@v2
              uses: actions/checkout@v4
            # - name: Cache Primes
            #   uses: actions/cache@v4
            #   with:
            #     path: ~/.npm
            #     key: node-modules-${{ hashFiles('client/packege-lock.json') }}
            - name: Install dependencies
              run: |
                cd client
                npm install
            - name: Test app
              run: |
                cd client
                npm run lint
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Get repository files@v2
              uses: actions/checkout@v4
            # - name: Cache Primes
            #   uses: actions/cache@v4
            #   with:
            #     path: ~/.npm
            #     key: node-modules-${{ hashFiles('client/packege-lock.json') }}
            - name: Install dependencies
              run: |
                cd client
                npm install
            - name: Test app
              run: |
                cd client
                npm run build
            - name: Deploy
              run: |
                cd client
                echo "Deploying!"